[package]
name = "pumpkin-api-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn .workspace = true
quote.workspace = true
proc-macro2.workspace = true
proc-macro-error2.workspace = true
