[package]
name = "pumpkin-registry"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-protocol.workspace = true
pumpkin-util.workspace = true

indexmap = { workspace = true, features = ["serde"] }

serde.workspace = true
serde_json.workspace = true
