[package]
name = "pumpkin-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error2.workspace = true

proc-macro2 = "1.0"
quote = "1.0"
syn.workspace = true
